apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: "mysql-service"
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_DATABASE
            value: todo_db
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/mysql
          - name: db-init-script
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data
        - name: db-init-script
          configMap:
            name: db-init-script
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
